server:
  port: 8090
  servlet:
    context-path: /
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.145.94:3306/jdbcstudy?useUnicode=true&characterEncoding=utf8&&useSSL=true
    username: root
    password: root
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  # src\main\java\com\air\airtest\entity  ?characterEncoding=utf-8&useSSL=false com\air\airtest\entity
  type-aliases-package: com.air.airtest.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
file:
  ip: 8090